load_defaults: 8.0.1
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://catalog:catalog@127.0.0.1:8983/solr/find-development" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://catalog:catalog@127.0.0.1:8983/solr/find-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/find-production" %>
