default: &default
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  encoding: unicode
  host: postgres
  password: <%= DockerSecrets.lookup(:database_password, ENV['DATABASE_PASSWORD']) %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV['DATABASE_USER'] %>
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
