default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: 5432
  password: <%= DockerSecrets.lookup(:database_password, ENV.fetch('DATABASE_PASSWORD', 'password')) %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>

development:
  <<: *default
  database: find_development

test:
  <<: *default
  database: find_test

staging:
  <<: *default
  database: find_staging

production:
  <<: *default
  database: find_production
