# scheduled job configuration - see Fugit gem docs for supported cron syntax

cleanup_guest_users:
  cron: 'every day at 4AM'
  class: 'CleanupGuestUsersJob'
cleanup_searches:
  cron: 'every day at 5AM'
  class: 'CleanupSearchesJob'
parse_art_collection:
  cron: 'every monday at 6AM'
  class: 'Discover::ParseArtCollectionJob'
