---
include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - secret_check
  - main_pipeline

secret_detection:
  stage: secret_check
  allow_failure: false
  artifacts:
    paths:
      - .pipeline.yml
    expire_in: 1 day
  tags:
    - build
  rules:
  - when: always

main:
  stage: main_pipeline
  needs:
    - secret_detection
  allow_failure: false
  trigger:
    include:
      - artifact: .pipeline.yml
        job: secret_detection
    strategy: depend
  rules:
  - if: "$CI_MERGE_REQUEST_IID"
  - if: "$CI_COMMIT_TAG"
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"