variables:
  FF_SCRIPT_SECTIONS: "true"
  GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${CI_PROJECT_NAME}/${CI_JOB_ID}"
  CI_DEBUG_SERVICES: "false"

include:
  - project: "devops/gitlab/ci-templates/ruby"
    ref: "sans-dind"
    file:
      - ".rspec.yml"
      - ".rubocop.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file:
      - ".trivy_container_scanning.yml"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/deploy/deploy@~latest
    inputs:
      deploy_environment: "staging"
      deploy_environment_url: "https://find-staging.library.upenn.edu"
      deploy_host: ${DEPLOY_HOST}
      job_suffix: "staging"
      valid_principals: ${VALID_PRINCIPALS}
      vault_auth_role: ${JWT_ROLE}
      vault_ssh_client_role: ${VAULT_SSH_CLIENT_ROLE}
      image_tag: ${CI_COMMIT_SHORT_SHA}
  - component: gitlab.library.upenn.edu/devops/gitlab/components/deploy/deploy@~latest
    inputs:
      deploy_environment: "production"
      deploy_environment_url: "https://find.library.upenn.edu"
      deploy_host: ${DEPLOY_HOST}
      job_suffix: "production"
      valid_principals: ${VALID_PRINCIPALS}
      vault_auth_role: ${JWT_ROLE}
      vault_ssh_client_role: ${VAULT_SSH_CLIENT_ROLE}
      image_tag: ${CI_COMMIT_SHORT_SHA}
  - component: gitlab.library.upenn.edu/devops/gitlab/components/general/vault_jwt_auth@~latest
    inputs:
      vault_auth_role: ${JWT_ROLE}
  - component: gitlab.library.upenn.edu/devops/gitlab/components/general/install_hashicorp_vault@~latest
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      docker_build_context: "rails_app/"
      dockerfile_path: "rails_app/"
      dockerfile_filename: "Dockerfile"
      stage: "build"
      docker_build_secrets: "--secret id=sidekiq_pro_credentials,env=SIDEKIQ_PRO_CREDENTIALS"
      docker_target: "base"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      docker_build_context: "rails_app/"
      dockerfile_path: "rails_app/"
      dockerfile_filename: "Dockerfile"
      stage: "build"
      docker_build_secrets: "--secret id=sidekiq_pro_credentials,env=SIDEKIQ_PRO_CREDENTIALS"
      docker_target: "development"
      docker_build_args: "--build-arg RAILS_ENV=development"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      dockerfile_path: "rails_app/"
      docker_build_context: "rails_app/"
      stage: "build"
      docker_build_secrets: "--secret id=sidekiq_pro_credentials,env=SIDEKIQ_PRO_CREDENTIALS"
      docker_additional_cache_targets: "base development"
      docker_build_args: "--build-arg RAILS_ENV=production"
      docker_target: "production"
      

  - component: gitlab.library.upenn.edu/devops/gitlab/components/sast/trivy@~latest
    inputs:
      docker_tag_to_scan: "${CI_COMMIT_SHA}"
      job_image_tag: "29-dind"
      needs:
        - "amend_manifest"
      stage: "test"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_finalize@~latest
    inputs:
      needs_copy:
        - trivy_scan
 
stages:
  - build_base
  - build_development
  - build_production
  - test
  - finalize
  - deploy
workflow:
  rules:
  - when: always

# -- Start - run unit tests in dev image
rspec_app_unit_test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}:${CI_COMMIT_SHORT_SHA}-development
  services:
    - name: postgres:16.12
      variables:
        POSTGRES_DB: "find_test"
        POSTGRES_PASSWORD: "rspec_test"
        POSTGRES_USER: "rspec_test"
    - name: bitnamilegacy/solr:9.6.1
      alias: solr
      entrypoint: [""]
      command: [
        "/bin/bash",
        "-c",
        "./opt/bitnami/scripts/solr/entrypoint.sh /opt/bitnami/scripts/solr/run.sh & \n
        for ((i = 0; i <= 9; i += 1)); do \n
          curl --silent 'http://solr:8983/api/' && break; \n
          echo 'Waiting for solr api to be ready'; \n
          sleep '10s'; \n
        done \n
        until [ -s \"${CI_PROJECT_DIR}/rails_app/solr/conf\" ]; do sleep 1; echo 'Waiting for solr conf to exist'; done \n
        .${ZK_SCRIPT_LOCATION}/zkcli.sh -zkhost 127.0.0.1:9983 -cmd upconfig -confname ${SOLR_TEST_CONFIGNAME} -confdir ${CI_PROJECT_DIR}/rails_app/solr/conf && \n
        ./opt/bitnami/solr/bin/solr create_collection -c ${SOLR_TEST_COLLECTION} -n ${SOLR_TEST_CONFIGNAME} \n
        wait"
      ]
      variables:
        SOLR_CLOUD_BOOTSTRAP: "yes"
        SOLR_ENABLE_AUTHENTICATION: "yes"
        SOLR_HOST: "solr"
        SOLR_JAVA_MEM: "-Xms4g -Xmx4g"
        SOLR_MODE: "solrcloud"
        SOLR_OPTS: "-Dsolr.disableConfigSetsCreateAuthChecks=true"
        SOLR_TEST_COLLECTION: "find-test"
        SOLR_TEST_CONFIGNAME: "find"
        ZK_CREATE_CHROOT: "true"
        ZK_SCRIPT_LOCATION: "/opt/bitnami/solr/server/scripts/cloud-scripts"
  extends:
    - .rspec
  variables:
    APP_URL: "find.test.com"
    CI: "true"
    DATABASE_HOST: "postgres"
    DATABASE_NAME: "find_test"
    DATABASE_PASSWORD: "rspec_test"
    DATABASE_USER: "rspec_test"
    FF_NETWORK_PER_BUILD: "true"
    RAILS_ENV: "test"
    RAILS_SYSTEM_TESTING_SCREENSHOT_HTML: "1"
    SOLR_URL: "http://solr:8983"
    SOLR_TEST_URL: http://solr:8983/solr/find-test
  before_script:
    - mkdir -p /tmp/indexing && cd /tmp/indexing
    - git clone -n --depth=1 --filter=tree:0 https://gitlab.library.upenn.edu/dld/catalog/catalog-indexing.git .
    - git sparse-checkout set --no-cone rails_app/solr/conf
    - git checkout
    - rm -fr ${CI_PROJECT_DIR}/rails_app/solr/*
    - mv /tmp/indexing/rails_app/solr/conf ${CI_PROJECT_DIR}/rails_app/solr
  script:
    - >
      for ((i = 0; i <= 9; i += 1)); do
        curl --silent "http://solr:8983/api/" "-H" "'Content-type:application/json'" && break
        echo "Waiting for solr api to be ready"
        sleep "10s"
      done
    - until [ -s "${CI_PROJECT_DIR}/rails_app/solr/conf" ]; do sleep 1; echo 'Waiting for solr conf to exist'; done
    - cd ${CI_PROJECT_DIR}/rails_app/
    - bundle add rspec_junit_formatter
    - bundle exec rake db:migrate
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml --profile 10 --tag ~type:system
  coverage: '/\(\d+.\d+\%\) covered/'
  artifacts:
    paths:
      - rails_app/tmp/coverage/index.html
      - rails_app/tmp/capybara
      - rails_app/rspec.xml
    expire_in: 1 week
    reports:
      junit: rails_app/rspec.xml
  rules:
    - if: $DISABLE_RSPEC_TEST == "true"
      when: never
    - exists:
        - rails_app/spec/**.rb
        - rails_app/spec/**/**.rb
  tags:
    - build

# -- integration tests for dev image
rspec_app_integration_test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}:${CI_COMMIT_SHORT_SHA}-development
  services:
    - name: ghcr.io/browserless/chromium:v2.38.4
      alias: chrome
      variables:
        PORT: 3333
        CONCURRENT: 1
        TIMEOUT: 1200000 # 20min should cover the system test run period
    - name: postgres:16.12
      variables:
        POSTGRES_DB: "find_test"
        POSTGRES_PASSWORD: "rspec_test"
        POSTGRES_USER: "rspec_test"
    - name: bitnamilegacy/solr:9.6.1
      alias: solr
      entrypoint: [""]
      command: [
        "/bin/bash",
        "-c",
        "./opt/bitnami/scripts/solr/entrypoint.sh /opt/bitnami/scripts/solr/run.sh & \n
        for ((i = 0; i <= 9; i += 1)); do \n
          curl --silent 'http://solr:8983/api/' && break; \n
          echo 'Waiting for solr api to be ready'; \n
          sleep '10s'; \n
        done \n
        until [ -s \"${CI_PROJECT_DIR}/rails_app/solr/conf\" ]; do sleep 1; echo 'Waiting for solr conf to exist'; done \n
        .${ZK_SCRIPT_LOCATION}/zkcli.sh -zkhost 127.0.0.1:9983 -cmd upconfig -confname ${SOLR_TEST_CONFIGNAME} -confdir ${CI_PROJECT_DIR}/rails_app/solr/conf && \n
        ./opt/bitnami/solr/bin/solr create_collection -c ${SOLR_TEST_COLLECTION} -n ${SOLR_TEST_CONFIGNAME} \n
        wait"
      ]
      variables:
        SOLR_CLOUD_BOOTSTRAP: "yes"
        SOLR_ENABLE_AUTHENTICATION: "yes"
        SOLR_HOST: "solr"
        SOLR_JAVA_MEM: "-Xms4g -Xmx4g"
        SOLR_MODE: "solrcloud"
        SOLR_OPTS: "-Dsolr.disableConfigSetsCreateAuthChecks=true"
        SOLR_TEST_COLLECTION: "find-test"
        SOLR_TEST_CONFIGNAME: "find"
        ZK_CREATE_CHROOT: "true"
        ZK_SCRIPT_LOCATION: "/opt/bitnami/solr/server/scripts/cloud-scripts"
  extends:
    - .rspec
  variables:
    APP_URL: "find.test.com"
    CI: "true"
    CHROME_URL: "ws://chrome:3333"
    DATABASE_HOST: "postgres"
    DATABASE_NAME: "find_test"
    DATABASE_PASSWORD: "rspec_test"
    DATABASE_USER: "rspec_test"
    FF_NETWORK_PER_BUILD: "true"
    RAILS_ENV: "test"
    RAILS_SYSTEM_TESTING_SCREENSHOT_HTML: "1"
    SOLR_URL: "http://solr:8983"
    SOLR_TEST_URL: http://solr:8983/solr/find-test
  before_script:
    - mkdir -p /tmp/indexing && cd /tmp/indexing
    - git clone -n --depth=1 --filter=tree:0 https://gitlab.library.upenn.edu/dld/catalog/catalog-indexing.git .
    - git sparse-checkout set --no-cone rails_app/solr/conf
    - git checkout
    - rm -fr ${CI_PROJECT_DIR}/rails_app/solr/*
    - mv /tmp/indexing/rails_app/solr/conf ${CI_PROJECT_DIR}/rails_app/solr
  script:
    - >
      for ((i = 0; i <= 9; i += 1)); do
        curl --silent "http://solr:8983/api/" "-H" "'Content-type:application/json'" && break
        echo "Waiting for solr api to be ready"
        sleep "10s"
      done
    - until [ -s "${CI_PROJECT_DIR}/rails_app/solr/conf" ]; do sleep 1; echo 'Waiting for solr conf to exist'; done
    - cd ${CI_PROJECT_DIR}/rails_app/
    - bundle add rspec_junit_formatter
    - bundle exec rake db:migrate
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml --profile 10 --tag type:system
  coverage: '/\(\d+.\d+\%\) covered/'
  artifacts:
    paths:
      - rails_app/tmp/coverage/index.html
      - rails_app/tmp/capybara
      - rails_app/rspec.xml
    expire_in: 1 week
    reports:
      junit: rails_app/rspec.xml
  rules:
    - if: $DISABLE_RSPEC_TEST == "true"
      when: never
    - exists:
        - rails_app/spec/**.rb
        - rails_app/spec/**/**.rb
  allow_failure: true
  tags:
    - build

rubocop_app_test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}:${CI_COMMIT_SHORT_SHA}-development
  extends:
    - .rubocop
  before_script:
    - cd ${CI_PROJECT_DIR}/rails_app/
  rules:
    - if: $DISABLE_RUBOCOP == "true"
      when: never
    - exists:
        - rails_app/.rubocop.yml
  tags:
    - build

reek_app_test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}:${CI_COMMIT_SHORT_SHA}-development
  before_script:
    cd ${CI_PROJECT_DIR}/rails_app/
  script:
    bundle exec reek app
  rules:
    - if: $DISABLE_REEK == "true"
      when: never
    - exists:
        - rails_app/.reek.yml
  allow_failure: false
  tags:
    - build
# -- End - test dev image

# Deploy staging
deploy_staging:
  only:
    - main

#Deploy production
deploy_production:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(\.[a-zA-Z0-9]+)?$/
#-- End - deployment
