---
- name: Create custom docker image using buildkit
  ansible.builtin.shell:
    cmd: |-
      docker build --build-arg RAILS_ENV="{{ catalog_find_rails_env }}" --target=development -t {{ catalog_find_image_name }}:{{ catalog_find_image_tag }} .
    chdir: "/catalog-find/ansible/roles/catalog-find/files/src/"
  environment:
    DOCKER_BUILDKIT: "true"
