collection:
  Publisher website: 100
  The New Republic Archive: 99
  Publishers Weekly Archive (1872- current): 98
  American Association for the Advancement of Science: 97
  Vogue Magazine Archive: 96
  'ProQuest Historical Newspapers: The New York Times': 95
  'ProQuest Historical Newspapers: Pittsburgh Post-Gazette': 94
  'ProQuest Historical Newspapers: The Washington Post': 93
  Wiley Online Library - Current Journals: 88
  Academic OneFile: 87
  Academic Search Premier: 86
  LexisNexis Academic: -1
  Factiva: -2
  Gale Cengage GreenR: -3
  Nature Free: -4
  DOAJ Directory of Open Access Journals: -5
  Highwire Press Free: -6
  Biography In Context: -7
interface:
  Highwire Press: 92
  Elsevier ScienceDirect: 91
  Nature: 90
  Elsevier ClinicalKey: 89
