# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.8'

gem 'alma'
gem 'blacklight', '~> 9'
gem 'blacklight_dynamic_sitemap'
gem 'blacklight-ris'
gem 'bootsnap', require: false
gem 'config'
gem 'devise'
gem 'devise-guests', '~> 0.8'
gem 'faraday'
gem 'faraday-retry'
gem 'honeybadger'
gem 'importmap-rails'
gem 'marc'
gem 'mini_racer'
gem 'observer', require: false
gem 'omniauth', '~> 2'
gem 'omniauth-saml'
gem 'pennmarc', '~> 1'
gem 'pg', '~> 1.6'
gem 'pg_search'
gem 'propshaft'
gem 'puma', '~> 6.5.0'
gem 'put'
gem 'rails', '~> 8'
gem 'requestjs-rails'
gem 'rsolr'
gem 'sidekiq-cron'
gem 'sidekiq-pro', source: 'https://gems.contribsys.com'
gem 'stimulus-rails'
gem 'summon'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'upennlib-rubocop', require: false
gem 'view_component', '~> 4.0'

group :development, :test do
  gem 'byebug'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 8.0.0'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'cuprite'
  gem 'webmock'
end
