# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.6'

# hoisted sprockets-rails to ensure sprockets loads before view_component to temporarily workaround known issue:
# https://github.com/ViewComponent/view_component/issues/2433
gem 'sprockets-rails'

gem 'alma'
gem 'blacklight', github: 'projectblacklight/blacklight', branch: 'release-8.x', ref: '70cd021fc56'
gem 'blacklight_dynamic_sitemap'
gem 'blacklight-ris'
gem 'bootsnap', require: false
gem 'bootstrap', '~> 5.1'
gem 'config'
gem 'devise'
gem 'devise-guests', '~> 0.8'
gem 'faraday'
gem 'faraday-retry'
gem 'honeybadger'
gem 'importmap-rails'
gem 'marc'
gem 'mini_racer'
gem 'omniauth'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-saml'
gem 'pennmarc', '~> 1'
gem 'pg', '~> 1.1'
gem 'pg_search'
gem 'puma', '~> 6.5.0'
gem 'put'
gem 'rails', '~> 7.1'
gem 'requestjs-rails'
gem 'rsolr'
gem 'sassc-rails'
gem 'sidekiq-cron'
gem 'sidekiq-pro', source: 'https://gems.contribsys.com'
gem 'stimulus-rails'
gem 'summon'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'upennlib-rubocop', require: false
gem 'view_component', '~> 4.0'

group :development, :test do
  gem 'byebug'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 7.0.0'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'cuprite'
  gem 'webmock'
end
