import '@hotwired/turbo-rails'
import '@rails/request.js'
import 'controllers'
import '@popperjs/core'
import * as bootstrap from 'bootstrap'
import 'tom-select'
import Blacklight from 'blacklight-frontend'
