load_defaults: 8.0.1
development:
  adapter: solr
  url: <%= Settings.solr_url %>
test: &test
  adapter: solr
  url: <%= Settings.solr_url %>
production:
  adapter: solr
  url: <%= Settings.solr_url %>
