default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: find_development

test:
  <<: *default
  database: find_test

production:
  <<: *default
  database: find_production
  username: find
  password: <%= ENV["READ_DATABASE_PASSWORD"] %>
