pennlibs_web_version: '0.1.1'
alma:
  api_key: '<%= DockerSecrets.lookup(:alma_api_key, Rails.application.credentials.alma_api_key) %>'
illiad:
  api_key: '<%= DockerSecrets.lookup(:illiad_api_key, Rails.application.credentials.illiad_api_key) %>'
locations:
  offsite:
    - lippb10
    - athstorcir
    - stor
    - storcirc
    - storcrstxt
    - storm
  unavailable:
    - athNoCirc
    - storNoCirc
    - vpunavail
    - vanpNocirc
  pickup:
    - - Van Pelt Library
      - VanPeltLib
    - - Lockers at Van Pelt Library
      - VPLOCKER
    - - Annenberg Library
      - AnnenLib
    - - Athenaeum Library
      - AthLib
    - - Holman Biotech Commons
      - BiomLib
    - - Chemistry Library
      - ChemLib
    - - Dental Medicine Library
      - DentalLib
    - - Lockers at Dental Medicine Library
      - DENTLOCKER
    - - Fisher Fine Arts Library
      - FisherFAL
    - - Library at the Katz Center
      - KatzLib
    - - Math/Physics/Astronomy Library
      - MPALib
    - - Museum Library
      - MuseumLib
    - - Ormandy Music and Media Center
      - MusicLib
    - - Pennsylvania Hospital Library - 800 Spruce St.
      - PAHospLib
    - - Veterinary Library - New Bolton Center
      - VetNBLib
    - - Veterinary Library - Penn Campus
      - VetPennLib
electronic_scoring:
  collection:
    Publisher website: 100
    The New Republic Archive: 99
    Publishers Weekly Archive (1872- current): 98
    American Association for the Advancement of Science: 97
    Vogue Magazine Archive: 96
    'ProQuest Historical Newspapers: The New York Times': 95
    'ProQuest Historical Newspapers: Pittsburgh Post-Gazette': 94
    'ProQuest Historical Newspapers: The Washington Post': 93
    Wiley Online Library - Current Journals: 88
    Academic OneFile: 87
    Academic Search Premier: 86
    LexisNexis Academic: -1
    Factiva: -2
    Gale Cengage GreenR: -3
    Nature Free: -4
    DOAJ Directory of Open Access Journals: -5
    Highwire Press Free: -6
    Biography In Context: -7
  interface:
    Highwire Press: 92
    Elsevier ScienceDirect: 91
    Nature: 90
    Elsevier ClinicalKey: 89

