---
solr_collections:
  - name: find-development
    configset: catalog-find
    replicas: 1
    shards: 1
  - name: find-test
    configset: catalog-find
    replicas: 1
    shards: 1

solr_configsets:
  - name: "catalog-find"
    path: "roles/catalog-find/files/src/solr/conf/"

solr_docker_image_tag: 9.6.1 # TODO: containers NOT starting Up!!!!!!!!!!!!!!!!!!!!!!!

solr_proxy_host: "catalog-find-dev.library.upenn.int"

solr_instances: 1

solr_collection_replicas: 1

solr_custom_env_variables:
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_ADMIN_USERNAME: "admin"
  SOLR_ADMIN_PASSWORD: "password"
