solr_url: <%= ENV.fetch('SOLR_URL', 'http://admin:password@catalog-indexing-dev.library.upenn.int/solr/catalog-indexing-development') %>
additional_results_sources:
  position: 1
  summon:
    access_id: 'upenn'
    base_url: 'upenn.summon.serialssolutions.com'
    api_key: <%= DockerSecrets.lookup(:summon_api_key, Rails.application.credentials.summon_api_key) %>