---
redis_docker_node_constraint: "catalog_find_redis"

redis_docker_stack_name: "catalog-find"

redis_network: "catalog-find-redis"

redis_users:
  - name: "sidekiq"
    acl_rules: "+@all ~*"
    password: "{{ catalog_find_vault_values.secret.redis_sidekiq_password }}"
    version: "{{ catalog_find_vault_values.metadata.version }}"
