solr_url: <%= ENV.fetch('SOLR_URL', 'http://catalog:catalog@127.0.0.1:8983/solr/find-development') %>
illiad_base_url: 'https://illiad.library.upenn.edu/ILLiadWebPlatform'
additional_results_sources:
  summon:
    access_id: 'upenn'
    base_url: 'upenn.summon.serialssolutions.com'